name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --force

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build
        run: ng build --configuration=production --base-href /pylab/

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name "${{ secrets.GH_NAME }}"
      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/pylab --no-silent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
