name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --force

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build
        run: ng build --configuration=production

      - name: Deploy to GitHub Pages
        run: |
          npx angular-cli-ghpages --dir=dist/pylab-deploy
          # Move index.html to root if it's in the 'browser' folder
          if [ -f dist/pylab-deploy/browser/index.html ]; then
            mv dist/pylab-deploy/browser/index.html dist/pylab-deploy/index.html
          fi
